<a href="https://colab.research.google.com/github/arelies-proximo/ML-Projects/blob/main/SciKit_Learn_(Classification_Models%2C_Tokenizer%2C_Saving_Models).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SCIKIT - LEARN

### **Classifying Data into Positive or Negative**

In [1]:
import pandas as pd
import json

In [2]:
file_name = "Books_small.json"

with open(file_name) as f:
  for line in f:
    print(line)
    break

{"reviewerID": "A1E5ZR1Z4OQJG", "asin": "1495329321", "reviewerName": "Pure Jonel \"Pure Jonel\"", "helpful": [0, 0], "reviewText": "Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters i

Need to extract reviewText and overall

In [3]:
with open(file_name) as f:
  for line in f:
    r = json.loads(line)
    print("Review: ", r["reviewText"])
    print("Stars: ", r["overall"])
    break

Review:  Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters in this novel were also truly touching.Overall, this novel was fantastic.  I can&#8217;t wait to read more and to find out wh

In [4]:
reviews = []
with open(file_name) as f:
  for line in f:
    r = json.loads(line)
    reviews.append((r["reviewText"], r["overall"]))

In [10]:
reviews[21:32:3]

[("Cambria Hebert is an author that I wait anxiously for her next book, knowing I will love it and Tattoo, does not disappoint. I loved her novel, Text, and this reminds me a lot of that book due to the suspense and immediate chemistry between the male and female lead. Brody, a cop coming from years undercover, is rusty at following his emotions. Taylor, an unspoiled beauty, determined to see under his facade. The story starts out with a bang and the action doesn't stop. As with all of her writings, it is well written, great dialog, fast paced, and pulls you in immediately! Cambria - Text was my favorite, but Tattoo gives it a run for its money!",
  5.0),
 ('Good plot/mystery and a strong woman investigator.  A little humor and a little romance whats not to like.  A very good cozy read.  Read all 3 books in this series and liked each one.',
  4.0),
 ('Very cute!', 4.0),
 ('I read a sample and it seemed ok.  The price was pretty high.  Took a chance and sad that I did.  Main characters 

In [11]:
reviews[21][0]
  #accessing only the text

"Cambria Hebert is an author that I wait anxiously for her next book, knowing I will love it and Tattoo, does not disappoint. I loved her novel, Text, and this reminds me a lot of that book due to the suspense and immediate chemistry between the male and female lead. Brody, a cop coming from years undercover, is rusty at following his emotions. Taylor, an unspoiled beauty, determined to see under his facade. The story starts out with a bang and the action doesn't stop. As with all of her writings, it is well written, great dialog, fast paced, and pulls you in immediately! Cambria - Text was my favorite, but Tattoo gives it a run for its money!"

In [12]:
reviews[21][1]

5.0

*Storing like above, in a list containing tuple is messy representation*

In [13]:
class Reviews:
  def __init__(self, text, rate):
    self.text = text
    self.score = rate
    self.sentiment = self.get_sentiment()

  def get_sentiment(self):
    if self.score <=2:
      return 'NEGATIVE'
    elif self.score == 3:
      return 'NEUTRAL'
    else:
      return 'POSITIVE'

In [14]:
review_list =[]

for i in reviews:
  review_list.append(Reviews(i[0], i[1]))

In [15]:
review_list[21].text

"Cambria Hebert is an author that I wait anxiously for her next book, knowing I will love it and Tattoo, does not disappoint. I loved her novel, Text, and this reminds me a lot of that book due to the suspense and immediate chemistry between the male and female lead. Brody, a cop coming from years undercover, is rusty at following his emotions. Taylor, an unspoiled beauty, determined to see under his facade. The story starts out with a bang and the action doesn't stop. As with all of her writings, it is well written, great dialog, fast paced, and pulls you in immediately! Cambria - Text was my favorite, but Tattoo gives it a run for its money!"

In [16]:
review_list[21].score

5.0

In [17]:
review_list[21].sentiment

'POSITIVE'

In [18]:
review_list[21].get_sentiment()

'POSITIVE'

In [19]:
len(review_list)

1000

### FOR CLASSIFYING WORDS, THE CONCEPT OF **BAG OF WORDS** IS USED.



https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html 

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

**stratify option**: will split such that the ratio of positive and negative labels is proportional in test and train.

**random state**: to get the same shuffle every time

In [23]:
training, test = train_test_split(review_list, test_size = 0.33, random_state=42, shuffle=True)

In [24]:
len(training)

670

In [25]:
len(test)

330

In [26]:
training[4].text

'Da Silva takes the divine by storm with this unique new novel.  She develops a world unlike any others while keeping it firmly in the real world.  This is a very well written and entertaining novel.  I was quite impressed and intrigued by the way that this solid storyline was developed, bringing the readers right into the world of the story.  I was engaged throughout and definitely enjoyed my time spent reading it.I loved the character development in this novel.  Da Silva creates a cast of high school students who actually act like high school students.  I really appreciated the fact that none of them were thrown into situations far beyond their years, nor did they deal with events as if they had decades of life experience under their belts.  It was very refreshing and added to the realism and impact of the novel.  The friendships between the characters in this novel were also truly touching.Overall, this novel was fantastic.  I can&#8217;t wait to read more and to find out what happe

In [27]:
test[3].text

"After all of William Lane Craig's book on philosophy and apologetics, I expected more depth.  The book is short and has some very interesting points but left me saying there has to be more."

In [28]:
test[3].score

3.0

In [29]:
test[3].sentiment

'NEUTRAL'

**Extracting the text and its respective output**

In [30]:
train_x = [x.text for x in training]
train_y = [x.sentiment for x in training]


test_x = [i.text for i in test]
test_y = [i.sentiment for i in test]

In [31]:
test_x[3]

"After all of William Lane Craig's book on philosophy and apologetics, I expected more depth.  The book is short and has some very interesting points but left me saying there has to be more."

In [32]:
test_y[3]

'NEUTRAL'

Creating a Vector of sentences from reviews


### **COUNT_VECTORIZER**

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

train_x_vectors = vectorizer.fit_transform(train_x)

Creating Testing Vectors

In [34]:
test_x_vectors = vectorizer.transform(test_x)
#ONLY TRANSFORM NOT FITTING

In [35]:
print(train_x[0])
print(train_x_vectors[0])

Vivid characters and descriptions. The author has created a tale that grabs your attention and I couldn't put it down.
  (0, 7086)	1
  (0, 1148)	1
  (0, 350)	2
  (0, 1800)	1
  (0, 6595)	1
  (0, 562)	1
  (0, 3054)	1
  (0, 1558)	1
  (0, 6475)	1
  (0, 6593)	1
  (0, 2895)	1
  (0, 7353)	1
  (0, 539)	1
  (0, 1515)	1
  (0, 5197)	1
  (0, 3545)	1
  (0, 2007)	1


*The column at which 1 occurs*

**THE TRAINING DATA IS READY**

In [36]:
print(train_x_vectors.shape)
print(len(train_y))

(670, 7372)
670


## CHOOSING THE PERFECT CLASSIFIER



REQUIRES UNDERSTANDING OF DIFFERENT CLASSIFIERS AND WHAT THEY ARE OFFERING.


https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html


```
classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis(),
]
```



LINEAR SUPPORT VECTOR CLASSIFIER/MACHINE

**SVM**

In [37]:
from sklearn import svm

clf_svc = svm.SVC(kernel='linear')

In [38]:
clf_svc.fit(train_x_vectors, train_y)

SVC(kernel='linear')

Checking/Predicting

In [39]:
print(test_x[0])
print(test_y[0])

test_x_vectors[0]

Every new Myke Cole book is better than the last, and this is no exception. If you haven't read the Shadow Ops series before start with Control Point, but go ahead and order Fortress Frontier and Breach Zone as well - you're going to want them.
POSITIVE


<1x7372 sparse matrix of type '<class 'numpy.int64'>'
	with 36 stored elements in Compressed Sparse Row format>

In [40]:
clf_svc.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

***Works perfectly.......!***

## USING DECISION TREE FOR CLASSIFICATION

In [41]:
from sklearn.tree import DecisionTreeClassifier

cls_dec = DecisionTreeClassifier()

cls_dec.fit(train_x_vectors, train_y)

DecisionTreeClassifier()

In [42]:
cls_dec.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

***Works Correctly..!***

### USING GAUSSIAN NAIVE BAYES

In [43]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors, train_y)

clf_gnb.predict(test_x_vectors[0])

TypeError: ignored

In [44]:
train_x_vectors.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [45]:
train_x_vectors.toarray().shape

(670, 7372)

In [46]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors.toarray(), train_y)

clf_gnb.predict(test_x_vectors.toarray()[0])

ValueError: ignored

In [47]:
test_x_vectors.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [48]:
test_x_vectors.toarray()[0].reshape(1,-1)

array([[0, 0, 0, ..., 0, 0, 0]])

In [50]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors.toarray(), train_y)




GaussianNB()

In [51]:
clf_gnb.predict(test_x_vectors.toarray()[0].reshape(1,-1))

array(['POSITIVE'], dtype='<U8')

### USING LOGISTIC REGRESSION

In [52]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression()

clf_log.fit(train_x_vectors, train_y)

print("\n\n")
clf_log.predict(test_x_vectors[0])

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array(['POSITIVE'], dtype='<U8')

## **EVALUATION**




USING **.score()** Method

*Mean Accuracy*

In [53]:
print("SVM: ", clf_svc.score(test_x_vectors, test_y))

print("\nDT: ", cls_dec.score(test_x_vectors, test_y))

print("\nLR: ", clf_log.score(test_x_vectors, test_y))

print("\nGNB: ", clf_gnb.score(test_x_vectors.toarray(), test_y))

SVM:  0.8242424242424242

DT:  0.7666666666666667

LR:  0.8303030303030303

GNB:  0.8121212121212121


In [54]:
print("SVM: ", clf_svc.score(test_x_vectors, test_y))

print("\nDT: ", cls_dec.score(test_x_vectors, test_y))

print("\nLR: ", clf_log.score(test_x_vectors, test_y))

print("\nGNB: ", clf_gnb.score(test_x_vectors.toarray(), test_y))

SVM:  0.8242424242424242

DT:  0.7666666666666667

LR:  0.8303030303030303

GNB:  0.8121212121212121


## **F1 SCORE**


To measure Models in DS

In [55]:
from sklearn.metrics import f1_score

In [56]:
f1_score(test_y, clf_svc.predict(test_x_vectors))

ValueError: ignored

*Target is MultiClass => Positive, Negative, Neutral*

In [57]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None)

array([0.22222222, 0.21052632, 0.91319444])

In [58]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTREL'])


#SPELLING OF NEUTRAL

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))


array([0.91319444, 0.22222222, 0.        ])

In [59]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.91319444, 0.22222222, 0.21052632])

The MODEL IS **NOT GOOD FOR NEGATIVE AND NEUTRAL MODELS**

GNB

In [60]:
f1_score(test_y, clf_gnb.predict(test_x_vectors.toarray()), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.89678511, 0.09090909, 0.08510638])

**Performs very poorly on Negative and Neutral (0.09 and 0.08)**

In [61]:
f1_score(test_y, cls_dec.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.87215412, 0.06451613, 0.10344828])

In [62]:
f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.91370558, 0.1       , 0.12244898])

All Models are not performing well on Negative and Neutral, ONLY Fit for Positive.

In [63]:
len(train_x)

670

In [64]:
train_y.count('POSITIVE')

552

In [65]:
pd.DataFrame(train_y).value_counts()

POSITIVE    552
NEUTRAL      71
NEGATIVE     47
dtype: int64

## ***The training data contains very less datasets for Neutral and Negative Targets***

The Models are highly biased towards POSITIVE.

***Downloading a bigger Datasets (10,000) reviews)***

In [66]:
f = open("Books_small_10000.json")

In [67]:
reviews = []
for line in f:
  r = json.loads(line)
  reviews.append((r["reviewText"], r["overall"]))

In [68]:
class Reviews:
  def __init__(self, text, rate):
    self.text = text
    self.score = rate
    self.sentiment = self.get_sentiment()

  def get_sentiment(self):
    if self.score <=2:
      return 'NEGATIVE'
    elif self.score == 3:
      return 'NEUTRAL'
    else:
      return 'POSITIVE'


review_list =[]

for i in reviews:
  review_list.append(Reviews(i[0], i[1]))

training, test = train_test_split(review_list, test_size = 0.33, random_state=42, shuffle=True)


train_x = [x.text for x in training]
train_y = [x.sentiment for x in training]


test_x = [i.text for i in test]
test_y = [i.sentiment for i in test]

In [69]:
pd.DataFrame(train_y).value_counts()

POSITIVE    5611
NEUTRAL      653
NEGATIVE     436
dtype: int64

***Still, there are 5K Positive Targets***


UNEVEN DISTRIBUTION

In [113]:
len(reviews)

10000

In [71]:
len(train_x)

6700

In [72]:
len(test_y)

3300

In [73]:
pd.DataFrame(test_y).value_counts()

POSITIVE    2767
NEUTRAL      325
NEGATIVE     208
dtype: int64

Two ways to equally distribute data:

  - Equal +ve and -ve in whole review
  - Equal +ve and -ve in training only

In [74]:
import copy
temp = copy.deepcopy(training[::])

In [75]:
len(temp)

6700

In [76]:
temp[0]

In [77]:
temp[3].text

'It was just one of those books that never went anywhere. I like books that get your attention in the beginning and not drag out until a quarter way through. I decided to give it an early death - delete!'

In [78]:
temp[3].sentiment

'NEGATIVE'

In [79]:
pos_train = [x for x in temp if x.sentiment == 'POSITIVE']

neg_train = [x for x in temp if x.sentiment == 'NEGATIVE']

neut_train = [x for x in temp if x.sentiment == 'NEUTRAL']

In [80]:
len(pos_train)

5611

In [81]:
len(neg_train)

436

In [82]:
len(neut_train)

653

In [83]:
len(temp)

6700

In [84]:
5611+436+653

6700

In [85]:
436+653

1089

In [86]:
pos_train[:1000][2]

In [87]:
len(pos_train[:1000])

1000

In [88]:
temp = neg_train+neut_train + pos_train[:1000]

In [89]:
len(temp)

2089

In [95]:
import random

random.shuffle(temp)

In [96]:
for i in temp[:10]:
  print(i.sentiment)

NEUTRAL
POSITIVE
POSITIVE
NEUTRAL
NEGATIVE
NEUTRAL
NEUTRAL
POSITIVE
POSITIVE
POSITIVE


**PERFECT**

In [97]:
type(training)

list

In [98]:
training = temp

In [99]:
train_x = [x.text for x in training]
train_y = [x.sentiment for x in training]


test_x = [i.text for i in test]
test_y = [i.sentiment for i in test]

In [100]:
pd.DataFrame(train_y).value_counts()

POSITIVE    1000
NEUTRAL      653
NEGATIVE     436
dtype: int64

In [101]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)
#ONLY TRANSFORM NOT FITTING

print(train_x_vectors.shape)
print(len(train_y))

(2089, 14745)
2089


In [102]:
#SVM
clf_svc = svm.SVC(kernel='linear')
clf_svc.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [103]:
#DT
cls_dec = DecisionTreeClassifier()
cls_dec.fit(train_x_vectors, train_y)

DecisionTreeClassifier()

In [104]:

#GNB
clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors.toarray(), train_y)


GaussianNB()

In [105]:

#Logistive Regression
clf_log = LogisticRegression()

clf_log.fit(train_x_vectors, train_y)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [106]:
#EVALUATION

print("SVM: ", clf_svc.score(test_x_vectors, test_y))

print("\nDT: ", cls_dec.score(test_x_vectors, test_y))

print("\nLR: ", clf_log.score(test_x_vectors, test_y))

print("\nGNB: ", clf_gnb.score(test_x_vectors.toarray(), test_y))

SVM:  0.6824242424242424

DT:  0.5703030303030303

LR:  0.7336363636363636

GNB:  0.4618181818181818


POSITIVE, NEGATIVE, NEUTRAL

In [107]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None)

array([0.33018868, 0.30072464, 0.81522634])

In [108]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.81522634, 0.33018868, 0.30072464])

In [109]:
f1_score(test_y, clf_gnb.predict(test_x_vectors.toarray()), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.62363086, 0.13429752, 0.18046234])

In [110]:
f1_score(test_y, cls_dec.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.73055436, 0.15864759, 0.20560748])

In [111]:
f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.85221186, 0.38610039, 0.33237272])

**Score has been decreased, F Score has increased a lil bit**

In [112]:
pd.DataFrame(test_y).value_counts()

POSITIVE    2767
NEUTRAL      325
NEGATIVE     208
dtype: int64

## UPDATING THE TEST DATASET AS WELL

In [122]:
print(len(reviews))

temp = copy.deepcopy(training[::])
pos_train = [x for x in temp if x.sentiment == 'POSITIVE']

neg_train = [x for x in temp if x.sentiment == 'NEGATIVE']

neut_train = [x for x in temp if x.sentiment == 'NEUTRAL']

temp = neg_train+neut_train + pos_train[:700]

random.shuffle(temp)

training = temp


10000


In [123]:
temp = copy.deepcopy(test[::])
pos_train = [x for x in temp if x.sentiment == 'POSITIVE']

neg_train = [x for x in temp if x.sentiment == 'NEGATIVE']

neut_train = [x for x in temp if x.sentiment == 'NEUTRAL']

temp = neg_train+neut_train + pos_train[:400]

random.shuffle(temp)

test = temp


In [124]:
train_x = [x.text for x in training]
train_y = [x.sentiment for x in training]


test_x = [i.text for i in test]
test_y = [i.sentiment for i in test]

In [125]:

pd.DataFrame(train_y).value_counts()

POSITIVE    700
NEUTRAL     653
NEGATIVE    436
dtype: int64

In [126]:

pd.DataFrame(test_y).value_counts()

POSITIVE    400
NEUTRAL     325
NEGATIVE    208
dtype: int64

In [127]:
vectorizer = CountVectorizer()

train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)
#ONLY TRANSFORM NOT FITTING

In [128]:
print(train_x_vectors.shape)
print(len(train_y))

(1789, 13539)
1789


In [129]:

#SVM
clf_svc = svm.SVC(kernel='linear')
clf_svc.fit(train_x_vectors, train_y)

#DT
cls_dec = DecisionTreeClassifier()
cls_dec.fit(train_x_vectors, train_y)


#GNB
clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors.toarray(), train_y)




#Logistive Regression
clf_log = LogisticRegression()

clf_log.fit(train_x_vectors, train_y)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [130]:
#EVALUATION

print("SVM: ", clf_svc.score(test_x_vectors, test_y))

print("\nDT: ", cls_dec.score(test_x_vectors, test_y))

print("\nLR: ", clf_log.score(test_x_vectors, test_y))

print("\nGNB: ", clf_gnb.score(test_x_vectors.toarray(), test_y))

SVM:  0.5659163987138264

DT:  0.43515541264737406

LR:  0.6280814576634512

GNB:  0.3729903536977492


In [131]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.66666667, 0.47555556, 0.51555556])

In [132]:
f1_score(test_y, clf_gnb.predict(test_x_vectors.toarray()), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.36708861, 0.31663327, 0.41632653])

In [133]:
f1_score(test_y, cls_dec.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.53777209, 0.29756098, 0.4       ])

In [134]:
f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.7327249 , 0.53110048, 0.56975037])

**NOT SO GOOD !!**

#Using TfidfTokenizer

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)

In [136]:

#SVM
clf_svc = svm.SVC(kernel='linear')
clf_svc.fit(train_x_vectors, train_y)

#DT
cls_dec = DecisionTreeClassifier()
cls_dec.fit(train_x_vectors, train_y)


#GNB
clf_gnb = GaussianNB()

clf_gnb.fit(train_x_vectors.toarray(), train_y)




#Logistive Regression
clf_log = LogisticRegression()

clf_log.fit(train_x_vectors, train_y)

LogisticRegression()

In [137]:
#EVALUATION

print("SVM: ", clf_svc.score(test_x_vectors, test_y))

print("\nDT: ", cls_dec.score(test_x_vectors, test_y))

print("\nLR: ", clf_log.score(test_x_vectors, test_y))

print("\nGNB: ", clf_gnb.score(test_x_vectors.toarray(), test_y))

SVM:  0.6505894962486602

DT:  0.45980707395498394

LR:  0.6430868167202572

GNB:  0.3783494105037513


In [138]:
f1_score(test_y, clf_svc.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.75384615, 0.5203252 , 0.60529986])

In [139]:
f1_score(test_y, clf_gnb.predict(test_x_vectors.toarray()), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.42329545, 0.27526882, 0.40172166])

In [140]:
f1_score(test_y, cls_dec.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.56996149, 0.30516432, 0.42965204])

In [141]:
f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=['POSITIVE', 'NEGATIVE', 'NEUTRAL'])

array([0.74509804, 0.49552239, 0.5958042 ])

### **SVM Tends to perform better**

**TUNING THE MODEL**



Using **GRID SEARCH**

In [142]:
help(svm.SVC)

Help on class SVC in module sklearn.svm._classes:

class SVC(sklearn.svm._base.BaseSVC)
 |  SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
 |  
 |  C-Support Vector Classification.
 |  
 |  The implementation is based on libsvm. The fit time scales at least
 |  quadratically with the number of samples and may be impractical
 |  beyond tens of thousands of samples. For large datasets
 |  consider using :class:`~sklearn.svm.LinearSVC` or
 |  :class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
 |  :class:`~sklearn.kernel_approximation.Nystroem` transformer or
 |  other :ref:`kernel_approximation`.
 |  
 |  The multiclass support is handled according to a one-vs-one scheme.
 |  
 |  For details on the precise mathematical formulation of the provided
 |  kernel functions and how `g

*It is used to pass different parameters to the model and keeps the best ones*



In [143]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel':('linear','rbf'), 'C':(1,4,8,16,32)}

svc = svm.SVC()

clf = GridSearchCV(svc, parameters, cv=5)

## *Fitting might take some time*

In [144]:
clf.fit(train_x_vectors, train_y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': (1, 4, 8, 16, 32), 'kernel': ('linear', 'rbf')})

In [145]:
clf.score(test_x_vectors, test_y)

0.6463022508038585

*Didn't do much but can be used in future to find what parameters might improve the model*

In [146]:
clf_svc.score(test_x_vectors, test_y)

0.6505894962486602

# **SAVING THE MODEL**

So didn't have to train the model again

In [147]:
import pickle

In [148]:
with open("sentiment_classifier.pkl", 'wb') as f:
  pickle.dump(clf, f)

In [151]:
with open("sentiment_classifier.pkl", 'rb') as f:
  loaded_clf = pickle.load(f)

  print(test_x[2])
  print(test_y[2])
  print(loaded_clf.predict(test_x_vectors[2]))

I was not sure about the book but thought it had to be good since I really enjoy both authors.  It packed a lot of action, imaginative other worldly events, yet combined with human action to survive and love.  In other words, a great story and highly recommended.  Going to Book 2 now...
POSITIVE
['POSITIVE']
