<a href="https://colab.research.google.com/github/arelies-proximo/ML-Projects/blob/main/AI%20Implementation/ANN_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ANN IMPLEMENTATION

BACKPROPAGATION algorithm

Basic Implementation, 

- Dot Product,  input and Hidden Layer's Wieght of Neuron
- Adding of Bias
- Through an Activation Function
- Output of A.F. to input to Output Layer
- Dot product with weight of O/P Layers' neurons
- Add the bias
- Through an Activation Function of Output Layer
- Predicted output is obtained
- Find the error in this prediction
- Update weight of hidden layer
- Update weight of Ouput layer
- Continue interation till completion of specified epochs

In [1]:
import numpy as np

In [9]:
#2 hours sleep, 9 hours study -> 70 marks
#8 sleep, 7 stuyd -> 92 marks
# qsleep, 10 study -> 60 marks

x = np.array(([2,9], [8,7], [1,10]), dtype=float)
y = np.array(([70], [92], [60]), dtype=float)


In [11]:
print(np.amax(x, axis=0))
  #max vals in each columns

[ 8. 10.]


In [12]:
x = x/np.amax(x,axis=0)

y = y/100


print('x:\n', x)
print('\ny: ', y)

x:
 [[0.25  0.9  ]
 [1.    0.7  ]
 [0.125 1.   ]]

y:  [[0.7 ]
 [0.92]
 [0.6 ]]


In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

#a sigmoid function
#to be used in

In [14]:
def derivative_sigmoid(x):
    return x*(1-x)

Number of iteration **epoch** and the learning rate **l**

In [15]:
epoch = 7000
lr = 0.2

Number of neurons in each layer

In [16]:
ip_layer_neurons = 2
  #two x columns

hdn_layer_nrns = 3
  #3 rows in x

op_layer_nrns = 1
  #single o/p for each x pairs

Weight of HIDDEN layers.

Bias of HIDDEN Layer

In [17]:
wh = np.random.uniform(size=(ip_layer_neurons, hdn_layer_nrns))
bh = np.random.uniform(size=(1,hdn_layer_nrns))


*With the help of numpy.random.uniform() method, we can get the **random samples from uniform distribution** and returns the random samples as numpy array by using this method*

In [18]:
wh

array([[0.02738028, 0.05792319, 0.7393125 ],
       [0.57445946, 0.04733436, 0.54133046]])

In [19]:
bh

array([[0.50063531, 0.75478289, 0.80310495]])

Weight and bias of Output Layer

In [20]:
wout = np.random.uniform(size=(hdn_layer_nrns, op_layer_nrns))
bout = np.random.uniform(size=(1, op_layer_nrns))

In [21]:
wout

array([[0.19516327],
       [0.69191632],
       [0.09253688]])

In [22]:
bout

array([[0.52868686]])

In [25]:

for i in range(epoch):
    hinp1= np.dot(x,wh)
        #first hidden layer input is cal by a dot product
        #Dot of input and weight of hidden layer neurons
    hinp = hinp1 + bh 
        #hidden layer input
        #ADD THE BIAS

    hlayer_act = sigmoid(hinp)
        #result of activation from hidden will be input to output layer

    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp)

    #Back Propagation
    EO = y-output
        #Error output layer
    outgrad = derivative_sigmoid(output)
        #output gradient

    d_output = EO*outgrad

    EH = d_output.dot(wout.T)
        #error hidden layer
        # .Target

    hiddengrad = derivative_sigmoid(hlayer_act)

    d_hiddenlayer = EH*hiddengrad

    wout += hlayer_act.T.dot(d_output)*lr
    #bout += np.sum(d_output, axis=0, keepdims=True)*lr

    wh+= x.T.dot(d_hiddenlayer)*lr
    #bh += np.sum(d_hiddenlayer, axis=0, keepdims=True)*lr

    if i%100==0:
      print(f"\ti: {i}\nEO: \n{EO}, \nEH: \n{EH}\nOutput: \n{output}\n-----------------------------")



	i: 0
EO: 
[[ 0.00775326]
 [-0.00183876]
 [-0.0065664 ]], 
EH: 
[[-2.62286371e-03  4.72519513e-03  4.85734445e-04]
 [ 2.10377807e-04 -3.79004136e-04 -3.89603727e-05]
 [ 2.48831211e-03 -4.48279499e-03 -4.60816511e-04]]
Output: 
[[0.69224674]
 [0.92183876]
 [0.6065664 ]]
-----------------------------
	i: 100
EO: 
[[ 0.00771049]
 [-0.00195096]
 [-0.00649487]], 
EH: 
[[-2.61046751e-03  4.70160690e-03  4.82079352e-04]
 [ 2.23115257e-04 -4.01843818e-04 -4.12030634e-05]
 [ 2.46351226e-03 -4.43693179e-03 -4.54940884e-04]]
Output: 
[[0.69228951]
 [0.92195096]
 [0.60649487]]
-----------------------------
	i: 200
EO: 
[[ 0.00766894]
 [-0.00205484]
 [-0.00642695]], 
EH: 
[[-2.59838895e-03  4.67858997e-03  4.78481513e-04]
 [ 2.34906271e-04 -4.22965977e-04 -4.32569218e-05]
 [ 2.43994391e-03 -4.39329805e-03 -4.49304579e-04]]
Output: 
[[0.69233106]
 [0.92205484]
 [0.60642695]]
-----------------------------
	i: 300
EO: 
[[ 0.00762856]
 [-0.00215099]
 [-0.00636237]], 
EH: 
[[-2.58661199e-03  4.65611638e

In [27]:
print("Input: \n", x)
print("Actual Output: \n",y)
print("Predicted Output: \n", output)

Input: 
 [[0.25  0.9  ]
 [1.    0.7  ]
 [0.125 1.   ]]
Actual Output: 
 [[0.7 ]
 [0.92]
 [0.6 ]]
Predicted Output: 
 [[0.69406504]
 [0.92292424]
 [0.60457737]]
